package simulator

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/hkt999rtk/rtk_billing/internal/payment"
)

const testSecret = "0123456789abcdef0123456789abcdef"

func TestClientCreatesHostedSetupWithSignedCanonicalRequest(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/internal/v1/setup-sessions" || r.Method != http.MethodPost {
			t.Fatalf("request=%s %s", r.Method, r.URL.Path)
		}
		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			t.Fatal(err)
		}
		encoded, _ := json.Marshal(body)
		// Marshal is deterministic for string-keyed maps and reproduces the body
		// generated by the client.
		if r.Header.Get("X-Payment-Simulator-Signature") != sign([]byte(testSecret), encoded) {
			t.Fatal("request signature mismatch")
		}
		if body["run_id"] != "run-client-1" || body["setup_session_id"] != "setup-1" || body["scenario"] != "success" {
			t.Fatalf("body=%+v", body)
		}
		_ = json.NewEncoder(w).Encode(map[string]any{
			"state": "requires_action", "hosted_url": "https://simulator.example/setup/token",
			"provider_code": "simulator_setup", "requires_user_action": true,
		})
	}))
	defer server.Close()
	client, err := New(Config{BaseURL: server.URL, SharedSecret: testSecret, RunID: "run-client-1", Timeout: time.Second})
	if err != nil {
		t.Fatal(err)
	}
	result, err := client.CreateSetup(context.Background(), payment.SetupRequest{
		AccountID: "account-1", LocalSessionID: "setup-1", IdempotencyKey: "key-1", CorrelationID: "correlation-1",
	})
	if err != nil || !result.RequiresUserAction || result.State != payment.PaymentIntentStateRequiresAction {
		t.Fatalf("result=%+v err=%v", result, err)
	}
}

func TestClientPreservesZeroDecimalTWDAmount(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var body struct {
			AmountMinor int64 `json:"amount_minor"`
		}
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			t.Fatal(err)
		}
		if body.AmountMinor != 301 {
			t.Fatalf("amount_minor=%d", body.AmountMinor)
		}
		_ = json.NewEncoder(w).Encode(map[string]any{
			"state": "succeeded", "provider_transaction_reference": "sim-txn-1",
			"provider_code": "simulator_success", "evidence": map[string]string{"scenario": "success"},
		})
	}))
	defer server.Close()
	client, err := New(Config{BaseURL: server.URL, SharedSecret: testSecret, RunID: "run-client-2", Timeout: time.Second})
	if err != nil {
		t.Fatal(err)
	}
	result, err := client.Charge(context.Background(), payment.ChargeRequest{
		IntentID: "intent-1", AmountMinor: 301, Currency: payment.CurrencyTWD,
		OpaqueMethodReference: "method-1", MerchantOrderReference: "order-1",
		IdempotencyKey: "key-1", CorrelationID: "correlation-1",
	})
	if err != nil || result.State != payment.PaymentIntentStateSucceeded {
		t.Fatalf("result=%+v err=%v", result, err)
	}
}

func TestClientRejectsUnsafeConfigurationAndAuthenticationFailure(t *testing.T) {
	if _, err := New(Config{BaseURL: "https://user:pass@example.test", SharedSecret: testSecret}); err == nil {
		t.Fatal("credential-bearing URL should fail")
	}
	if _, err := New(Config{BaseURL: "https://example.test", SharedSecret: testSecret, RunID: "unsafe/run"}); err == nil {
		t.Fatal("unsafe run ID should fail")
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusUnauthorized) }))
	defer server.Close()
	client, err := New(Config{BaseURL: server.URL, SharedSecret: testSecret, RunID: "run-client-3", Timeout: time.Second})
	if err != nil {
		t.Fatal(err)
	}
	_, err = client.Query(context.Background(), payment.QueryRequest{IntentID: "intent-1", AmountMinor: 1, Currency: payment.CurrencyTWD})
	if err == nil {
		t.Fatal("authentication failure should propagate")
	}
}
